version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: velocity-postgres
    environment:
      POSTGRES_DB: birdsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: velocity-redis
    ports:
      - "6379:6379"
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: velocity-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - backend
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    mem_limit: 1g

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: velocity-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - elasticsearch
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/birdsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_ELASTICSEARCH_HOST: elasticsearch
      SPRING_DATA_ELASTICSEARCH_PORT: 9200
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
#      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
