server:
  port: 8080

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis.cache: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, metrics, threaddump, heapdump, prometheus, beans

spring:
  application:
    name: birds
  data:
    elasticsearch:
      host: localhost
      port: 9200
      repositories:
        enabled: true
      index:
        auto-create: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/birdsdb
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  redis:
    host: localhost
    port: 6379
    password:
    repositories:
      enabled: false
